# This workflow triggers when things are merged into the `master` branch
# - run tests
# - publish to staging channel

name: Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🗝 Expose secrets
        run: echo '{"TWITTER":"${{ secrets.TWITTER }}","YOUTUBE_RELEASE_API_KEY":"${{ secrets.YOUTUBE_RELEASE_API_KEY }}","AMPLITUDE":"${{ secrets.AMPLITUDE }}","GITHUB_SHA":"${{ github.sha }}","SENTRY_DSN":"${{ secrets.SENTRY_DSN }}","SENTRY_AUTH_TOKEN":"${{ secrets.SENTRY_AUTH_TOKEN }}"}' > constants/Keys.json

      - name: 🧪 Run tests
        run: npm test

      - name: 🚀 Publish preview
        run: npx expo-optimize . && npm run publish

      - name: 💬 Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: Ilshidur/action-slack@master
        with:
          args: ':shipitparrot: App has been published to the `default` release channel. Check your Expo Go app to test changes.'
